apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
   matchLabels:
     app: nginx-pod 
  template:
   metadata: 
    labels:
      app: nginx-pod
   spec:   
     containers:
     - name: ngnix-contanier
       image: nginx
       ports:
       - containerPort: 80
