apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 labels:
   env: prod-deployment
   version: 1.2.3
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: frontend
    spec:
     containers:
     - name: gb-container
       image:  paulczar/gb-frontend:v5
       resources:
         requests: 
           cpu: 100m
           memory: 100Mi
       env:
        - name : GET_HOSTS_FROM
          value: dns

       ports:
       - containerPort: 80 

