apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    env: database-prod

spec:
  selector:
     app.kubernetes.io/name: mongo
     app.kubernetes.io/component: backend
  ports:
  - port: 27107
    targetPort:  27107

