apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
     app.kubernetes.io/name: guestbook
     app.kubernetes.io/component: frontend
  type: LoadBalancer
  ports:
  - port: 80  
